### ISSUE TITLE
Add alertsnitch to docker-compose.yml

### ISSUE THREAD

**Issue by fabricat** [yakshaving-art/alertsnitch#3]
That'd be great if the `docker-compose.yml` could contain both `mysql` and `alertsnitch`.

I currently use the container at `registry.gitlab.com/yakshaving.art/alertsnitch` only, in `--dry-run` mode.

**Comment by pcarranza** [comment]
Hey @fabricat in version 0.2.1 you have a docker-compose that includes alertsnitch and connects to the database for testing.

Enjoy.
